spring:
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: root
      password: mojiti
    datasource:
      url: jdbc:h2:mem:soa_service_api
      username: sa
      password:
      driverClassName: org.h2.Driver
      sql-script-encoding: UTF-8
      schema: classpath:schema.sql

logging.level.org.springframework: DEBUG
